data:
  tokenizer_path: "./models/gpt-clean-16000.json"
  train_path: "./data/gutenberg_10M"
  eval_path: "./data/babylm_dev_clean"
  seq_length: 128
  eval_samples: 8192

model:
  type: "Llama"  # Llama for 700M model
  name: "Llama-700M-G10"  # Updated the model name to reflect Llama 700M
  hidden_size: 1536  # Llama 700M hidden size
  intermediate_size: 6144  # Llama 700M intermediate size
  n_layer: 16  # Llama 700M has 16 layers
  n_head: 32  # Llama 700M has 32 attention heads

training:
  lr: 1e-4  # Lower learning rate for stability
  batch_size: 128  # Larger batch size for 700M model
  num_epochs: 4
  gradient_accumulation_steps: 8  # Adjust gradient accumulation based on batch size
  warmup_steps: 500  # Warmup steps remain the same
  fp16: True  # Keep mixed precision for reduced memory usage

logging: 
  wandb: True
  project: "babylm-dev"
  output_dir: "./models/"
