data:
  tokenizer_path: "./models/gpt-clean-16000.json"
  train_path: "./data/gutenberg_10M"
  eval_path: "./data/babylm_dev_clean"
  seq_length: 128
  eval_samples: 8192

model:
  type: "Llama"  # Still Llama for 3B
  name: "Llama-3B-G10"  # Updated the model name to reflect Llama 3B
  hidden_size: 3200  # Llama 3B hidden size
  intermediate_size: 8640  # Llama 3B intermediate size
  n_layer: 26  # Llama 3B has 26 layers
  n_head: 32  # Llama 3B has 32 attention heads

training:
  lr: 1e-4  # Lower learning rate for stability with larger models
  batch_size: 32  # Moderate batch size for 3B model, adjust based on available GPU memory
  num_epochs: 4
  gradient_accumulation_steps: 32  # Adjust gradient accumulation based on batch size
  warmup_steps: 500  # Increased warmup for larger models
  fp16: True  # Keep mixed precision for reduced memory usage

logging: 
  wandb: True
  project: "babylm-dev"
  output_dir: "./models/"
